import type { Metadata } from 'next';
import '@/styles/main.scss';
import Menu from '@/app/_components/Menu';
import CustomCursor from '@/app/_components/CustomCursor';

export const metadata: Metadata = {
  title: '김수현 포트폴리오',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomCursor />
        <Menu />
        {children}
        {modal}
      </body>
    </html>
  );
}
