import type { Metadata } from 'next';
import '@/styles/main.scss';
import Menu from '@/components/Menu';
import CustomCursor from '@/components/CustomCursor';

export const metadata: Metadata = {
  title: '김수현 포트폴리오',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomCursor />
        <Menu />
        {children}
      </body>
    </html>
  );
}
